services:
  depasoalimentos-db:
    image: postgres:16
    container_name: depasoalimentos-postgres
    environment:
      POSTGRES_DB: depasoalimentos
      POSTGRES_USER: depasoalimentos
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - depasoalimentos_postgres_data:/var/lib/postgresql/data

volumes:
  depasoalimentos_postgres_data:
